export { default as CommunityEditGeneral } from './CommunityEditGeneral'
export { default as CommunityEditCourse } from './CommunityEditCourse'
export { default as CommunityEditModeration } from './CommunityEditModeration'
export { default as CommunityEditAccess } from './CommunityEditAccess'
export { default as CommunityMediaSection } from './CommunityMediaSection'
